linters:
  enable-all: true
  fast: true
  disable:
    - gci
    - gofumpt
    - scopelint
    - testpackage
    - godox
    - tagliatelle
    - ifshort

service:
  golangci-lint-version: 1.48

linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  misspell:
    ignore-words:
      - zzz
  lll:
    line-length: 200
  govet:
    # report about shadowed variables
    check-shadowing: true
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
gocritic:
  enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style
    - security

issues:
  exclude-rules:
    - path: "cmd/*"
      linters:
        - funlen
        - dupl
    - path: ".*_test.go"
      linters:
        - funlen
        - dupl
